# -----------------------
# 서버 인코딩 설정
# -----------------------
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# -----------------------
# Spring 어플리케이션 설정
# -----------------------
spring:
  application:
    name: Reading Note API

  # H2 Database 설정 (기본: 인메모리)
  datasource:
    url: jdbc:h2:mem:readingdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 웹 콘솔
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA 설정
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop # 시작할 때 생성, 종료할 때 삭제
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

    show-sql: true # SQL 쿼리 콘솔 출력
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅
        use_sql_comments: true # SQL 주석 추가

  # SQL 초기화
  sql:
    init:
      mode: always # data.sql 항상 실행

# -----------------------
# 로깅 설정
# -----------------------
logging:
  level:
    root: INFO
    com.example.readingnoteapi : DEBUG
    org.hibernate.SQL : DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
