# 파일 모드 프로파일 ( --spring.profiles.active=file )

# -----------------------
# 서버 인코딩 설정
# -----------------------
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# -----------------------
# Spring 어플리케이션 설정
# -----------------------
spring:
  application:
    name: MyWebService

  #Thymeleaf 설정
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false # 개발 시 false 설정 -> 실시간 반영

  # H2 Database 설정 (파일)
  datasource:
    url: jdbc:h2:file:./data/boardapi;AUTO_SERVER=true   # 파일 모드
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 웹 콘솔
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA 설정
  jpa:
    defer-datasource-initialization: true
    hibernate:
      # ddl-auto: create-drop # 시작할 때 생성, 종료할 때 삭제
      ddl-auto: update #파일 모드에서 스키마 업데이트만
      # ddl-auto: validate # 운영 환경에서 구조 검증(Entity와 DB 스키마 검증)만 하고 싶을 때
    show-sql: true # SQL 쿼리 콘솔 출력
    properties:
      hibernate:
        format_sql: true # SQL 포맷팅
        use_sql_comments: true # SQL 주석 추가

  # SQL 초기화
  sql:
    init:
      # mode: always # data.sql 항상 실행
      mode: never # 파일 모드에서는 초기 데이터 실행 안함

# -----------------------
# 로깅 설정
# -----------------------
logging:
  level:
    root: INFO
    com.example.board : DEBUG
    org.hibernate.SQL : DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
